### ISSUE TITLE
Api-gateway không có service?

### ISSUE THREAD

**Issue by NguyenPC2015** [hoalongnatsu/microservices#1]
Cho mình hỏi sao bạn không tạo service cho api-gateway để load balancer và để thông ra bên ngoài?
Các deployment khác đều có service đi kèm tại sao gateway, news, category lại ko tạo service cho nó?
Mong bạn giải thích.

**Comment by quanhuynhhoangphuc** [comment]
À, này do mình hướng dẫn cách deploy hệ thống thôi, Load Balancer thì phải môi trường cloud mới có sẵn, còn ở dưới on-premise thì phải cài ingress, nên mình không có thêm vào đây. Còn bạn muốn expose traffic ra ngoài thì bạn viết file Ingress cho API Gateway nha. Còn news, category service thì ta sẽ không có expose traffic cho nó, mà tụi nó sẽ được gọi thông qua API Gateway, API Gateway sẽ dùng NATS để communicate với các service. Này là kiến trúc của framework moleculer js. Bạn có thể đọc docs của nó để hiểu thêm nha. https://moleculer.services/docs/0.14/
